version: '3'
services:

  registry:
    image: registry:2  
    container_name: registry
    ports:
      - "5000:5000"  
    volumes:
      - registry_data:/var/lib/registry 
    networks:
      - registry-net

  registry-ui:
    image: joxit/docker-registry-ui:latest 
    container_name: registry-ui
    ports:
      - "8080:80" 
    environment:
      - REGISTRY_TITLE=SUPMIT Private Registry  
      - REGISTRY_URL=http://localhost:5000 
    depends_on:
      - registry  
    networks:
      - registry-net

volumes:
  registry_data:

networks:
  registry-net: